version: "3"

services:
  mysql:
    image: mysql:5.7
    container_name: presta-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=admin
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - prestashop-net

  prestashop:
    image: prestashop/prestashop
    container_name: some-prestashop
    environment:
      - DB_SERVER=presta-mysql
      - DB_USER=root
      - DB_PASSWORD=admin
      - DB_NAME=prestashop
    ports:
      - "8080:80"
    volumes:
      - prestashop-data:/var/www/html
    depends_on:
      - mysql
    networks:
      - prestashop-net

networks:
  prestashop-net:
    driver: bridge

volumes:
  mysql-data:
  prestashop-data:
